In [1]:
import pandas as pd
import numpy as np
import time
start_time = time.time()


def find_empty_cell(board):
    for row in range(9):
        for col in range(9):
            if board[row][col] == 0:
                return row, col
    return None

def is_valid_move(board, row, col, num):
    # Check the row
    if num in board[row]:
        return False
    
    # Check the column
    if num in [board[i][col] for i in range(9)]:
        return False
    
    # Check the 3x3 box
    box_row, box_col = row // 3 * 3, col // 3 * 3
    for i in range(box_row, box_row + 3):
        for j in range(box_col, box_col + 3):
            if board[i][j] == num:
                return False
    
    return True

def update_legal_values(board, row, col, num, legal_values):
    for i in range(9):
        if i != col and board[row][i] == 0:
            legal_values[row][i].discard(num)
        
        if i != row and board[i][col] == 0:
            legal_values[i][col].discard(num)
    
    box_row, box_col = row // 3 * 3, col // 3 * 3
    for i in range(box_row, box_row + 3):
        for j in range(box_col, box_col + 3):
            if (i != row or j != col) and board[i][j] == 0:
                legal_values[i][j].discard(num)

def initialize_legal_values(board):
    legal_values = [[set(range(1, 10)) for _ in range(9)] for _ in range(9)]
    for row in range(9):
        for col in range(9):
            if board[row][col] != 0:
                update_legal_values(board, row, col, board[row][col], legal_values)
    return legal_values

def forward_checking_sudoku(board):
    empty_cell = find_empty_cell(board)
    
    if not empty_cell:
        return True  # No empty cells, the puzzle is solved
    
    row, col = empty_cell
    legal_values = initialize_legal_values(board)

    for num in legal_values[row][col]:
        if is_valid_move(board, row, col, num):
            board[row][col] = num
            update_legal_values(board, row, col, num, legal_values)

            if forward_checking_sudoku(board):
                return True

            # If this value doesn't lead to a solution, backtrack
            board[row][col] = 0
    
    return False

# Example Sudoku puzzle (0 represents empty cells)
if __name__ == "__main__":
    # Load the Kaggle dataset (replace 'sudoku_dataset.csv' with your dataset file)
    dataset = pd.read_csv('sudoku.csv')

    for index, row in dataset.iterrows():
        puzzle = np.array(list(map(int, list(row['puzzle'])))).reshape(9, 9)
        
        if forward_checking_sudoku(puzzle):
           print(f"Solved Puzzle {index + 1}:")
           for row in puzzle:
              print(row)
        else:
           print(f"No solution found for Puzzle {index + 1}.")
        print("=" * 30)
        if index == 3000:
            break
end_time = time.time()
print(start_time)
print(end_time)




Solved Puzzle 1:
[6 7 9 5 1 8 2 4 3]
[5 4 3 7 2 9 6 1 8]
[8 2 1 6 3 4 9 5 7]
[7 9 4 3 5 2 1 8 6]
[3 5 8 4 6 1 7 2 9]
[2 1 6 8 9 7 5 3 4]
[4 8 5 2 7 6 3 9 1]
[9 6 2 1 8 3 4 7 5]
[1 3 7 9 4 5 8 6 2]
Solved Puzzle 2:
[3 7 1 9 8 6 5 2 4]
[8 4 6 5 2 1 3 7 9]
[5 9 2 4 7 3 8 6 1]
[4 6 3 8 1 9 7 5 2]
[2 8 5 3 4 7 9 1 6]
[7 1 9 6 5 2 4 3 8]
[6 3 4 1 9 5 2 8 7]
[1 2 8 7 3 4 6 9 5]
[9 5 7 2 6 8 1 4 3]
Solved Puzzle 3:
[7 4 8 3 9 1 5 6 2]
[3 6 5 2 4 8 7 9 1]
[9 1 2 6 7 5 4 8 3]
[4 2 1 7 8 6 9 3 5]
[5 8 9 4 1 3 2 7 6]
[6 7 3 5 2 9 8 1 4]
[8 3 4 9 6 2 1 5 7]
[2 9 6 1 5 7 3 4 8]
[1 5 7 8 3 4 6 2 9]
Solved Puzzle 4:
[2 9 8 3 1 7 6 4 5]
[7 6 4 2 8 5 1 3 9]
[1 5 3 9 4 6 2 7 8]
[3 2 7 1 6 8 9 5 4]
[9 8 1 4 5 3 7 2 6]
[6 4 5 7 9 2 8 1 3]
[5 3 9 8 2 1 4 6 7]
[8 7 2 6 3 4 5 9 1]
[4 1 6 5 7 9 3 8 2]
Solved Puzzle 5:
[1 4 2 8 9 5 6 3 7]
[9 7 5 1 3 6 8 2 4]
[8 3 6 7 4 2 5 1 9]
[3 9 8 4 6 7 1 5 2]
[4 5 1 3 2 8 7 9 6]
[2 6 7 5 1 9 3 4 8]
[5 2 9 6 7 3 4 8 1]
[6 1 3 2 8 4 9 7 5]
[7 8 4 9 5 1 2 6 3]
Solved Puzzle 6