In [1]:
#Solving Sudoku using Integer Linear Programming (ILP) is a more complex task compared to backtracking algorithms like Dancing Links. 
#To solve Sudoku using ILP in Python, you can use a library like PuLP, 
#which provides an interface for defining and solving linear programming problems. 
#You'll also need an LP solver like CBC or GLPK to solve the generated ILP problem. 
#Here's an example of how to solve Sudoku using ILP with PuLP and the CBC solver:*/

import pandas as pd
import numpy as np
import pulp
import time

start_time = time.time()

def solve_sudoku_ilp(board):
    size = len(board)
    
    # Create a LP problem
    problem = pulp.LpProblem("Sudoku Problem", pulp.LpMinimize)
    
    # Create binary variables for each cell (row, column, and value)
    choices = pulp.LpVariable.dicts("Choice", (range(size), range(size), range(1, size + 1)), cat=pulp.LpBinary)
    
    # Add constraints for each cell to ensure only one value per cell
    for row in range(size):
        for col in range(size):
            problem += pulp.lpSum(choices[row][col][val] for val in range(1, size + 1)) == 1
    
    # Add constraints for each row to ensure all values are distinct
    for row in range(size):
        for val in range(1, size + 1):
            problem += pulp.lpSum(choices[row][col][val] for col in range(size)) == 1
    
    # Add constraints for each column to ensure all values are distinct
    for col in range(size):
        for val in range(1, size + 1):
            problem += pulp.lpSum(choices[row][col][val] for row in range(size)) == 1
    
    # Add constraints for each 3x3 subgrid to ensure all values are distinct
    subgrid_size = int(size**0.5)
    for i in range(0, size, subgrid_size):
        for j in range(0, size, subgrid_size):
            for val in range(1, size + 1):
                problem += pulp.lpSum(choices[i + x][j + y][val] for x in range(subgrid_size) for y in range(subgrid_size)) == 1
    
    # Add initial values as constraints
    for row in range(size):
        for col in range(size):
            value = board[row][col]
            if value != 0:
                problem += choices[row][col][value] == 1
    
    # Solve the ILP problem
    problem.solve(pulp.PULP_CBC_CMD(msg=False))
    
    # Extract the solution into a new Sudoku board
    solution = [[0 for _ in range(size)] for _ in range(size)]
    for row in range(size):
        for col in range(size):
            for val in range(1, size + 1):
                if choices[row][col][val].value() == 1:
                    solution[row][col] = val
    
    return solution


if __name__ == "__main__":
    # Load the Kaggle dataset (replace 'sudoku_dataset.csv' with your dataset file)
    dataset = pd.read_csv('sudoku.csv')

    for index, row in dataset.iterrows():
        puzzle = np.array(list(map(int, list(row['puzzle'])))).reshape(9, 9)
        original_board=np.copy(puzzle)
        solution = solve_sudoku_ilp(puzzle)
        if solution:
           print(f"Solved Puzzle {index + 1}:")
           for row in solution:
              print(row)
        else:
           print(f"No solution found for Puzzle {index + 1}.")
        print("\nOriginal Puzzle:")
        print(original_board)
        print("=" * 30)
        if index == 9:
            break
end_time = time.time()
print(start_time)
print(end_time)

print(end_time-start_time)




/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pulp/pulp.py:1352: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")


Solved Puzzle 1:
[6, 7, 9, 5, 1, 8, 2, 4, 3]
[5, 4, 3, 7, 2, 9, 6, 1, 8]
[8, 2, 1, 6, 3, 4, 9, 5, 7]
[7, 9, 4, 3, 5, 2, 1, 8, 6]
[3, 5, 8, 4, 6, 1, 7, 2, 9]
[2, 1, 6, 8, 9, 7, 5, 3, 4]
[4, 8, 5, 2, 7, 6, 3, 9, 1]
[9, 6, 2, 1, 8, 3, 4, 7, 5]
[1, 3, 7, 9, 4, 5, 8, 6, 2]

Original Puzzle:
[[0 7 0 0 0 0 0 4 3]
 [0 4 0 0 0 9 6 1 0]
 [8 0 0 6 3 4 9 0 0]
 [0 9 4 0 5 2 0 0 0]
 [3 5 8 4 6 0 0 2 0]
 [0 0 0 8 0 0 5 3 0]
 [0 8 0 0 7 0 0 9 1]
 [9 0 2 1 0 0 0 0 5]
 [0 0 7 0 4 0 8 0 2]]
Solved Puzzle 2:
[3, 7, 1, 9, 8, 6, 5, 2, 4]
[8, 4, 6, 5, 2, 1, 3, 7, 9]
[5, 9, 2, 4, 7, 3, 8, 6, 1]
[4, 6, 3, 8, 1, 9, 7, 5, 2]
[2, 8, 5, 3, 4, 7, 9, 1, 6]
[7, 1, 9, 6, 5, 2, 4, 3, 8]
[6, 3, 4, 1, 9, 5, 2, 8, 7]
[1, 2, 8, 7, 3, 4, 6, 9, 5]
[9, 5, 7, 2, 6, 8, 1, 4, 3]

Original Puzzle:
[[3 0 1 0 8 6 5 0 4]
 [0 4 6 5 2 1 0 7 0]
 [5 0 0 0 0 0 0 0 1]
 [4 0 0 8 0 0 0 0 2]
 [0 8 0 3 4 7 9 0 0]
 [0 0 9 0 5 0 0 3 8]
 [0 0 4 0 9 0 2 0 0]
 [0 0 8 7 3 4 0 9 0]
 [0 0 7 2 0 8 1 0 3]]
Solved Puzzle 3:
[7, 4, 8, 3, 9, 1, 5, 6, 2]
[

In [1]:
#16X16
#In this code:

#We use PuLP to create a linear programming problem with binary decision variables representing the values in each cell.
#We add constraints to ensure that each cell contains exactly one value, each row contains distinct values, each column contains distinct values, and each 3x3 subgrid contains distinct values.
#Initial values from the Sudoku puzzle are added as constraints.
#We use the CBC solver to solve the ILP problem.
#The solution is extracted from the solved linear program and returned as a Sudoku board.


import pandas as pd
import numpy as np
import pulp
import time

start_time = time.time()

def solve_sudoku_ilp(board):
    size = len(board)
    
    # Create a LP problem
    problem = pulp.LpProblem("Sudoku Problem", pulp.LpMinimize)
    
    # Create binary variables for each cell (row, column, and value)
    choices = pulp.LpVariable.dicts("Choice", (range(size), range(size), range(1, size + 1)), cat=pulp.LpBinary)
    
    # Add constraints for each cell to ensure only one value per cell
    for row in range(size):
        for col in range(size):
            problem += pulp.lpSum(choices[row][col][val] for val in range(1, size + 1)) == 1
    
    # Add constraints for each row to ensure all values are distinct
    for row in range(size):
        for val in range(1, size + 1):
            problem += pulp.lpSum(choices[row][col][val] for col in range(size)) == 1
    
    # Add constraints for each column to ensure all values are distinct
    for col in range(size):
        for val in range(1, size + 1):
            problem += pulp.lpSum(choices[row][col][val] for row in range(size)) == 1
    
    # Add constraints for each 4x4 subgrid to ensure all values are distinct
    subgrid_size = int(size**0.5)
    for i in range(0, size, subgrid_size):
        for j in range(0, size, subgrid_size):
            for val in range(1, size + 1):
                problem += pulp.lpSum(choices[i + x][j + y][val] for x in range(subgrid_size) for y in range(subgrid_size)) == 1
    
    # Add initial values as constraints
    for row in range(size):
        for col in range(size):
            value = board[row][col]
            if value != 0:
                problem += choices[row][col][value] == 1
    
    # Solve the ILP problem
    problem.solve(pulp.PULP_CBC_CMD(msg=False))
    
    # Extract the solution into a new Sudoku board
    solution = [[0 for _ in range(size)] for _ in range(size)]
    for row in range(size):
        for col in range(size):
            for val in range(1, size + 1):
                if choices[row][col][val].value() == 1:
                    solution[row][col] = val
    
    return solution


if __name__ == "__main__":
    # Load the Kaggle dataset (replace 'sudoku_dataset.csv' with your dataset file)
    dataset = pd.read_csv('sudoku16.csv')

    for index, row in dataset.iterrows():
        puzzle = np.array(list(map(int, list(row['puzzle'].split(" "))))).reshape(16, 16)
        original_board=np.copy(puzzle)
        solution = solve_sudoku_ilp(puzzle)
        if solution:
           print(f"Solved Puzzle {index + 1}:")
           for row in solution:
              print(row)
        else:
           print(f"No solution found for Puzzle {index + 1}.")
        print("\nOriginal Puzzle:")
        print(original_board)
        print("=" * 30)
        if index == 9:
            break
end_time = time.time()
print(start_time)
print(end_time)
print(end_time-start_time)



/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pulp/pulp.py:1352: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")


Solved Puzzle 1:
[8, 10, 2, 4, 3, 12, 11, 13, 15, 7, 16, 9, 14, 1, 5, 6]
[5, 7, 11, 14, 2, 16, 6, 8, 10, 13, 1, 12, 4, 3, 9, 15]
[6, 9, 3, 1, 5, 10, 15, 7, 8, 4, 14, 2, 11, 12, 13, 16]
[15, 13, 12, 16, 4, 9, 14, 1, 5, 6, 11, 3, 2, 8, 7, 10]
[11, 15, 9, 7, 12, 8, 16, 5, 1, 14, 2, 6, 10, 13, 3, 4]
[14, 1, 10, 8, 13, 3, 9, 2, 16, 12, 4, 11, 5, 6, 15, 7]
[4, 16, 5, 12, 10, 6, 7, 14, 13, 3, 9, 15, 8, 11, 2, 1]
[2, 3, 13, 6, 11, 4, 1, 15, 7, 5, 10, 8, 9, 16, 14, 12]
[9, 14, 15, 11, 16, 5, 13, 6, 3, 2, 12, 7, 1, 4, 10, 8]
[16, 2, 6, 13, 8, 7, 3, 4, 11, 1, 5, 10, 15, 9, 12, 14]
[10, 8, 1, 5, 14, 15, 12, 9, 6, 16, 13, 4, 7, 2, 11, 3]
[7, 12, 4, 3, 1, 11, 2, 10, 9, 15, 8, 14, 6, 5, 16, 13]
[13, 11, 7, 9, 15, 2, 10, 12, 4, 8, 6, 16, 3, 14, 1, 5]
[1, 6, 14, 10, 9, 13, 8, 3, 12, 11, 7, 5, 16, 15, 4, 2]
[12, 5, 16, 15, 6, 14, 4, 11, 2, 10, 3, 1, 13, 7, 8, 9]
[3, 4, 8, 2, 7, 1, 5, 16, 14, 9, 15, 13, 12, 10, 6, 11]

Original Puzzle:
[[ 8 10  2  4  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 5  7 11 14  0  